#!/usr/bin/env php
<?php

const REWRITE_HOME = __DIR__;

require __DIR__ . '/lib.php';

$config = [];

if (file_exists($global_file = __DIR__ . '/configs/_global.php')) {
    $_global = require $global_file;

    if (!is_array($_global)) {
        error_log("Global config must return an array");

        exit(1);
    }

    $config = $_global + $config;
}

if ($config_file = @$argv[1]) {
    if (!preg_match(',^/,', $config_file)) {
        $config_file = __DIR__ . '/configs/' . $config_file . '.php';
    }

    if (!file_exists($config_file)) {
        error_log("Config file [$config_file] does not exist");

        exit(1);
    }

    if (!is_array($_local = require $config_file)) {
        error_log("Local config must return an array");

        exit(1);
    }

    $config = $_local + $config;
}

$config = (object) $config;

if ($config_file = @$config->portal_config_file) {
    if (!file_exists($config_file)) {
        error_log("Portal config file [$config_file] does not exist");

        exit(1);
    }

    if (!is_object($_portal = json_decode(file_get_contents($config_file)))) {
        error_log("Portal config is expected to be an object");

        exit(1);
    }
}

if (!config_valid($config)) {
    error_log('Invalid config');

    exit(1);
}

$meta_handle = null;
$meta_pointer = 0;
$meta_line_num = 0;
$meta_record_tables = [];

if ($master_meta_file = @$config->master_log_meta) {
    if (!is_file($master_meta_file)) {
        die("master_meta_file [$master_meta_file] not found\n");
    }

    if (!$meta_handle = fopen($master_meta_file, 'r')) {
        die("could not open master meta file [$master_meta_file] for reading\n");
    }
}

$fifo = stream_get_meta_data(tmpfile())['uri'];

@unlink($fifo); // just in case gc is too slow

if (!posix_mkfifo($fifo, 0600)) {
    throw new Exception("Could not create the temporary FIFO");
}

echo "FIFO: $fifo\n";

shell_exec('rm -rf "' . $config->db_home . '"; mkdir "' . $config->db_home . '";');

$import_cmd = "import '$fifo'";
$refresh_cmd = 'refresh';

echo "Importing...\n";

echo jars_command($import_cmd, $config) . "\n";

log_fineprint('Starting jars process ' . jars_command($import_cmd, $config) . '...');

$jars_process = proc_open(jars_command($import_cmd, $config), [
   0 => ['pipe', 'r'],
   1 => ['pipe', 'w'],
   2 => ['pipe', 'w'],
], $pipes, '/tmp');

if (!proc_get_status($jars_process)['running']) {
    error_log('Oops, looks like we could not start the process');

    exit(1);
}

log_fineprint("Successfully started jars process.");

[$jars_input, $jars_output, $jars_error] = $pipes;

unset($pipes);

stream_set_blocking($jars_error, false);
stream_set_blocking($jars_output, false);

usleep(500000);

$error = trim(fgets($jars_error), "\n");
$output = trim(fgets($jars_output), "\n");

if ($output) {
    log_output($output);
}

if ($error) {
    log_error($error);
}

if (false == $master_log_handle = fopen($config->master_log, 'r')) {
    error_log('Could open master log for reading');

    exit(1);
}

log_fineprint("Opening feedback fifo for READ...");

$feedback_handle = fopen($fifo, 'r');

log_fineprint("Successfully opened feedback fifo for READ.");

stream_set_blocking($feedback_handle, false);

$old_pointer = 0;
$id_map = [];
$failed = false;
$fakelog = [];
$id_offset = 0;

$table = null;

while (false !== $log_entry = array_pop($fakelog) ?: fgets($master_log_handle)) {
    $result = preg_match('/^([0-9a-f]{64}) ([0-9-]+) ([0-9:]+) (\[.*\])/', $log_entry, $matches);

    if (!$result) {
        error_log("Unrecognised line format");
        log_fineprint(substr($log_entry, 0, 200));

        exit(1);
    }

    [, $hash, $date, $time, $json] = $matches;

    $data = json_decode($json);

    if ($closure = $config->rewrite ?? null) {
        call_r($data, $closure);
    }

    if (!count($data)) {
        log_fineprint('skipping entry ' . $date . ' ' . $time);

        continue;
    }

    if ($meta_handle) {
        $meta_record_tables = [];
        $meta_line = fgets($meta_handle);
        $meta_line_num++;

        if (!preg_match('/^([a-f0-9]{64}) (.*)/', $meta_line, $matches)) {
            die("Unrecognised meta line format on line $meta_line_num\n");
        }

        [, $meta_version, $meta_line] = $matches;

        // break into entries
        $entries = explode(' ', $meta_line);

        foreach ($entries as $entry) {
            if (!preg_match('/^\+(.*)/', $entry, $matches)) {
                continue;
            }

            $meta_pointer++;

            [$meta_table, $meta_id] = explode(':', $matches[1]);

            if (!preg_match('/^[a-z0-9_]+$/', $meta_table)) {
                die("Invalid table in meta on line $meta_line_num: $meta_table\n");
            }

            if (!preg_match('/^[a-f0-9]{64}$/', $meta_id)) {
                die("Invalid id in meta on line $meta_line_num: $meta_id\n");
            }

            $meta_record_tables[] = "$meta_table:$meta_id";
        }
    }

    id_map_r($data, $config->incoming_links ?? [], $config->mapping_exclude ?? []);

    $translated = $date . ' ' . $time . ' ' . json_encode($data);

    log_fineprint(substr(trim($translated, "\n"), 0, 150) . (strlen($log_entry) > 150 ? '...' : ''));

    fwrite($jars_input, $translated . "\n");

    $linesCreated = 0;
    $unexpecteds = [];

    for ($finished = false; !$finished; usleep(100)) {
        while ($output = trim(fgets($jars_output), "\n")) {
            log_output($output);
        }

        while ($error = trim(fgets($jars_error), "\n")) {
            log_error($error);
        }

        $output = $error = null;

        while ($feedback = trim(fgets($feedback_handle), "\n")) {
            log_feedback($feedback);

            if (preg_match('/^issued: (\S+) (\S+)/', $feedback, $matches)) {
                $linesCreated++;

                [, $pointer, $id] = $matches;

                if ($meta_handle) {
                    $expected = @$meta_record_tables[$linesCreated - 1];
                    $got = "$table:$id";

                    if ($got !== $expected) {
                        $unexpecteds[] = "expected [$expected], issued [$got], pointer [$pointer]";
                    }
                }

                $old_pointer++;
                $old_id = null;

                if (!@$config->id_offsetting) {
                    $display_old_pointer = $old_pointer;
                    $old_id = @$config->old_n2h ? ($config->old_n2h)($old_pointer) : n2h_old($old_pointer);
                } elseif ($id_offset) {
                    $display_old_pointer = $pointer - $id_offset;
                    $old_id = trim(shell_exec(jars_command('n2h ' . $display_old_pointer, $config)));
                }

                if ($old_id) {
                    $id_map[$old_id] = $id;
                    $id_map["new:$id"] = $old_id;

                    log_fineprint("Saved map $old_id → $id ($display_old_pointer → $pointer)");
                }

                if ($callable = $config->after_issue ?? null) {
                    $_fakelog = [];
                    $callable($pointer, $id, $old_pointer, $old_id, $date . ' ' . $time, $_fakelog);
                    $fakelog = array_merge($fakelog, $_fakelog);
                }
            } elseif (preg_match('/^importline (\S+)/', $feedback, $matches)) {
                $table = $matches[1];
            } elseif ($feedback === 'entry imported') {
                $finished = true;
            }
        }

        if (!proc_get_status($jars_process)['running']) {
            error_log('Oops, look as though the process died');
            $failed = true;
            break 2;
        }
    }

    if ($meta_handle) {
        $expected_count = count($meta_record_tables);

        if ($linesCreated !== $expected_count || $unexpecteds) {
            if ($linesCreated !== $expected_count) {
                echo "Wrong number of lines created, expected $expected_count got $linesCreated on meta line [$meta_line_num] (version [$meta_version])\n";
            }

            foreach ($unexpecteds as $unexpected) {
                echo "Meta check failed: $unexpected\n";
            }

            die();
        }
    }
}

fclose($master_log_handle);
fclose($jars_input);

stream_set_blocking($jars_error, true);
stream_set_blocking($feedback_handle, true);
stream_set_blocking($jars_output, true);

log_output(stream_get_contents($jars_output));
log_error(stream_get_contents($jars_error));

log_feedback(stream_get_contents($feedback_handle));

fclose($feedback_handle);
fclose($jars_output);
fclose($jars_error);

proc_close($jars_process);

unlink($fifo);

if ($meta_handle) {
    fclose($meta_handle);
}

if (!$failed) {
    if ($map_file = @$config->id_map_file) {
        file_put_contents($map_file, json_encode($id_map, JSON_UNESCAPED_SLASHES));
    }

    if ($config->refresh ?? true) {
        echo "Refreshing...\n" . jars_command($refresh_cmd, $config, true) . "\n";
        shell_exec(jars_command($refresh_cmd, $config));
    }
}